### ISSUE TITLE
Not compatible with the current version of the IDE (202.* upgraded to 203.*)

### ISSUE THREAD

**Issue by JonathanATyler** [jsbeckr/tailwind-idea#6]
I upgraded PHPStorm to latest build and am now seeing this message...

Plugin 'Tailwind Intellisense' (version '0.0.7') is not compatible with the current version of the IDE, because it requires build 202.* or older but the current build is PS-203.5981.175

**Comment by jsbeckr** [comment]
That's true. Please try the official Jetbrains Plugin: https://plugins.jetbrains.com/plugin/15321-tailwind-css

I think I will retire this plugin once enough people upgraded to the newest versions of the IDEs.
